var dataCacheName = 'cache-db-gmbtn-1';
var cacheName = 'cache-gmbtn-1';
var filesToCache = [
    '/Content/csscompressor/cssmoi.min.css',
    '/Content/cssBG/jquery-ui.css',
    '/Content/csscompressor/Autocomplete.css',
    '/Content/csscompressor/colcss.min.css',
    '/Content/csscompressor/font-awesome.min.css',
    '/Content/csscompressor/rateit.min.css',
    '/Content/cssBG/sweetalert2.min.css',
    '/Content/csscompressor/cart.min.css',
    '/Content/cssBG/jquery.elevator.css',
    '/Content/csscompressor/cssphone.min.css',
    '/Scripts/JsBg/jquery.min.js',
    '/Scripts/JsBgcompressor/jquery.sticky.min.js',
    '/Scripts/JsBgcompressor/owl.carousel.min.js',
    '/Content/csscompressor/ykienkhachhang.min.css',
    '/Scripts/JsBg/bootstrap.min.js',
    '/Scripts/JsBg/jquery.countdown.min.js',
    '/Scripts/JsBg/jquery.bxslider.min.js',
    '/Scripts/JsBg/jquery.actual.min.js',
    '/Scripts/JsBg/chosen.jquery.min.js',
    '/Scripts/JsBg/jquery.parallax-1.1.3.js',
    '/Scripts/JsBg/jquery.elevateZoom.min.js',
    '/Scripts/JsBg/jquery.fancybox.pack.js',
    '/Scripts/JsBg/jquery.fancybox-media.js',
    '/Scripts/JsBg/jquery.fancybox-thumbs.js',
    '/Scripts/JsBg/jquery.arcticmodal.js',
    '/Scripts/JsBgcompressor/main.min.js',
    '/Scripts/jquery-ui.js',
    '/Scripts/autocompleteMasterpage.js',
    '/Scripts/autocompleteDropdown.js',
    '/Scripts/sweetalert2.min.js',
    '/Scripts/jquery.validate.min.js',
    '/Scripts/jquery.validate.unobtrusive.min.js',
    '/Scripts/JsBgcompressor/jquery.elevator.min.js',
    '/Scripts/JsBg/SearchSmartDown.js',
    '/images/logomoi.png',
    '/Upload/files/quote-01.png',
    '/Upload/files/quote-02.png',
    '/Upload/files/shop-01.png?width=804&height=534',
    '/Upload/files/shop-02.png?width=804&height=534',
    '/Upload/files/shop-04.png?width=804&height=534',
    '/Upload/files/shop-03.png?width=804&height=534',
    '/images/maps.png',
    '/Upload/Files/banner-01-compressor.png',
    '/Upload/Files/banner-02-compressor.png',
    '/Upload/Files/banner-chinh-innisfree-soybean-compressor.png',
    '/Upload/Files/Kem-chong-Nang-Beauty-Garden-03-compressor.png',
    '/Upload/Files/banner-01-compressor.png',
    '/Upload/Files/banner-02-compressor.png'
];

self.addEventListener('install', function (e) { console.log('[ServiceWorker] Install'); e.waitUntil(caches.open(cacheName).then(function (cache) { console.log('[ServiceWorker] Caching app shell'); return cache.addAll(filesToCache) })) }); self.addEventListener('activate', function (e) { console.log('[ServiceWorker] Activate'); e.waitUntil(caches.keys().then(function (keyList) { return Promise.all(keyList.map(function (key) { if (key !== cacheName && key !== dataCacheName) { console.log('[ServiceWorker] Removing old cache', key); return caches.delete(key) } })) })); return self.clients.claim() }); self.addEventListener('fetch', function (e) { console.log('[Service Worker] Fetch', e.request.url); var dataUrl = 'https://query.yahooapis.com/v1/public/yql'; if (e.request.url.indexOf(dataUrl) > -1) { e.respondWith(caches.open(dataCacheName).then(function (cache) { return fetch(e.request).then(function (response) { cache.put(e.request.url, response.clone()); return response }) })) } else { e.respondWith(caches.match(e.request).then(function (response) { return response || fetch(e.request) })) } });